# Documentation:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    pull-request-title-pattern: "build: Update ${dependency-name} from ${version-from} to ${version-to}"
    versioning-strategy: "auto"
    registries:
      - maven-central
      - gradle-plugin-portal
